In [1]:
import numpy as np

# Créer un objet NumPy ndarray

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Tableaux 

In [9]:
# tableau 0-D
arr = np.array(32)
print(arr)
# Tableau 1-D
arr = np.array([1, 31, 3, 4, 55])
print(arr)
#tableau 2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
#tableau 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

32
[ 1 31  3  4 55]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Vérifier le nombre de dimensions :

In [11]:
a = np.array(32)
b = np.array([1, 2, 31, 4, 55])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [14]:
arr = np.array([0,55,66,9,88])

print(arr.dtype)

int32


In [19]:
arr = np.array([102,55,666,999,2020,2022,2023,22])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)


[ 102   55  666  999 2020 2022 2023   22]
int32


In [20]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [22]:
arr = np.array([[[2020,2021,2022], [3020,3020,3333]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[2020 2021 2022]
 [3020 3020 3333]]
[[ 7  8  9]
 [10 11 12]]


In [23]:
arr1 = np.array([99,100,102,55])

arr2 = np.array([21,22,55,99])

arr = np.concatenate((arr1, arr2))

print(arr)

[ 99 100 102  55  21  22  55  99]


In [24]:
arr1 = np.array([99,100,102,55])

arr2 = np.array([21,22,55,99])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[ 99  21]
 [100  22]
 [102  55]
 [ 55  99]]


In [30]:
arr = np.array([41, 42, 55,66,99,22,36,99,102])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True, True, False, False, True, True]
[ 55  66  99  99 102]
